// src/lib/components/editable-grid/editable-grid.component.tsx
import { type EditableGridController } from "$/lib/components/editable-grid/editable-grid-controller";
import { EditableGridContext } from "$/lib/components/editable-grid/editable-grid.context";
import { getCssGridTemplateFromGridLines } from "$/lib/components/editable-grid/editable-grid.utils";
import { GridCellsRenderer } from "$/lib/components/editable-grid/grid-cells-renderer.component";
import { GridOverlaysRenderer } from "$/lib/components/editable-grid/grid-overlays-renderer";
import { useStore } from "$/lib/utils/store/useStore";

export interface EditableGridProps {
  grid: EditableGridController;
}

export const EditableGrid: React.FC<EditableGridProps> = ({ grid }) => {
  useStore(grid, grid);

  return (
    <EditableGridContext.Provider value={grid}>
      <div
        className="relative grid h-full w-full [--grid-gap:4px]"
        style={{
          gridTemplate: getCssGridTemplateFromGridLines(grid.getLines()),
        }}
        ref={grid.setContainer}
        onMouseMove={(event) =>
          grid.events.container.mouseMove.emit(event.nativeEvent)
        }
        role="grid"
        tabIndex={0}
      >
        <GridCellsRenderer />
        <GridOverlaysRenderer />
      </div>
    </EditableGridContext.Provider>
  );
};

// src/lib/components/editable-grid/editable-grid.svelte
<script lang="ts">
	import EditableGridCellMergeIndicator from '$lib/components/editable-grid/editable-grid-cell-merge-indicator.svelte';
	import EditableGridCell from '$lib/components/editable-grid/editable-grid-cell.svelte';
	import { EditableGridController } from '$lib/components/editable-grid/editable-grid-controller';
	import EditableGridOverlays from '$lib/components/editable-grid/editable-grid-overlays.svelte';
	import { gridContext, gridEvents } from '$lib/components/editable-grid/editable-grid.model';
	import { getCssGridTemplateFromGridLines } from '$lib/components/editable-grid/editable-grid.utils';
	import '$lib/modules/interaction-stack/interaction-stack';
	import { setContext } from 'svelte';

	export let grid: EditableGridController;

	setContext(gridContext, grid);

	let lines = grid.lines;
	let cells = grid.cells;
	let overlays = grid.overlays;
</script>

<div
	class="relative grid h-full w-full [--grid-gap:4px]"
	style:grid-template={getCssGridTemplateFromGridLines($lines)}
	bind:this={grid.gridContainer}
	on:mousemove={(event) => grid.eventEmitter.emit(gridEvents.container.mouseMove, event)}
	role="grid"
	tabindex="0"
>
	{#each $cells as cell}
		<EditableGridCell {cell}>
			<EditableGridCellMergeIndicator {cell} />
		</EditableGridCell>
	{/each}

	<EditableGridOverlays overlays={$overlays} />
</div>
