// src/lib/components/editable-grid/overlay-renderers/cells-overlay-renderer.component.tsx
import {
  type EditableGridOverlayDataFor,
  type OverlayTargetType,
} from "$/lib/components/editable-grid/editable-grid-overlay.model";
import {
  useGrid,
  useGridCells,
} from "$/lib/components/editable-grid/editable-grid.context";
import React, { useMemo } from "react";

export interface CellsOverlayRendererProps {
  overlay: EditableGridOverlayDataFor<OverlayTargetType.Cells>;
}

export const CellsOverlayRenderer: React.FC<CellsOverlayRendererProps> = ({
  overlay,
}) => {
  const grid = useGrid();
  const cells = useGridCells();

  const target = useMemo(
    () => overlay.target ?? cells,
    [cells, overlay.target],
  );

  const Component = overlay.component ?? React.Fragment;

  return (
    <>
      {target?.map((cell, index) => (
        <div
          key={index}
          className={"group relative"}
          role="presentation"
          style={{
            gridColumnStart: cell.bounds.col.start.name,
            gridColumnEnd: cell.bounds.col.end.name,
            gridRowStart: cell.bounds.row.start.name,
            gridRowEnd: cell.bounds.row.end.name,
            zIndex: overlay.zIndex,
            pointerEvents: overlay.pointerEvents,
          }}
          onClick={(event) =>
            grid?.events.cell.click.emit({ cell, originalEvent: event })
          }
          onMouseEnter={(event) =>
            grid?.events.cell.mouseEnter.emit({ cell, originalEvent: event })
          }
          onMouseMove={(event) =>
            grid?.events.cell.mouseMove.emit({ cell, originalEvent: event })
          }
          onMouseLeave={(event) =>
            grid?.events.cell.mouseLeave.emit({ cell, originalEvent: event })
          }
        >
          <Component />
        </div>
      ))}
    </>
  );
};

// src/lib/components/editable-grid/overlay-renderers/cells-overlay-renderer.svelte
<script lang="ts">
	import { EditableGridController } from '$lib/components/editable-grid/editable-grid-controller';
	import type {
		EditableGridOverlayDataFor,
		OverlayTargetType,
	} from '$lib/components/editable-grid/editable-grid-overlay.model';
	import { gridContext } from '$lib/components/editable-grid/editable-grid.model';
	import { getContext } from 'svelte';

	const grid = getContext<EditableGridController>(gridContext);
	let cells = grid.cells;

	export let overlay: EditableGridOverlayDataFor<OverlayTargetType.Cells>;
	$: target = overlay.target ?? $cells;
</script>

{#each target as cell}
	<div
		style:grid-row-start={cell.bounds.row.start.name}
		style:grid-row-end={cell.bounds.row.end.name}
		style:grid-column-start={cell.bounds.col.start.name}
		style:grid-column-end={cell.bounds.col.end.name}
		style:z-index={overlay.zIndex}
		style:pointer-events={overlay.pointerEvents}
		class="group relative"
		on:click={(event) => grid.events.cell.click.emit({ originalEvent: event, cell })}
		on:mousemove={(event) => grid.events.cell.mouseMove.emit({ originalEvent: event, cell })}
		on:mouseenter={(event) => grid.events.cell.mouseEnter.emit({ originalEvent: event, cell })}
		on:mouseleave={(event) => grid.events.cell.mouseLeave.emit({ originalEvent: event, cell })}
		role="presentation"
	>
		<svelte:component this={overlay.component} />
	</div>
{/each}
