// src/lib/components/editable-grid/overlay-renderers/container-overlay-renderer.svelte
<script lang="ts">
	import type {
	    EditableGridOverlayDataFor,
	    OverlayTargetType,
	} from '$/lib/components/editable-grid/editable-grid-overlay.model';
	import { gridEndLine, gridStartLine } from '$/lib/components/editable-grid/editable-grid.model';

	export let overlay: EditableGridOverlayDataFor<OverlayTargetType.Container>;
</script>

<div
	role="presentation"
	style:grid-row-start={gridStartLine}
	style:grid-row-end={gridEndLine}
	style:grid-column-start={gridStartLine}
	style:grid-column-end={gridEndLine}
	class="relative"
	style:z-index={overlay.zIndex}
	style:pointer-events={overlay.pointerEvents}
>
	<svelte:component this={overlay.component} />
</div>

// src/lib/components/editable-grid/overlay-renderers/container-overlay-renderer.component.tsx
import {
  type EditableGridOverlayDataFor,
  type OverlayTargetType,
} from "$/lib/components/editable-grid/editable-grid-overlay.model";
import { gridBoundingLines } from "$/lib/components/editable-grid/editable-grid.model";
import React from "react";

export interface ContainerOverlayRendererProps {
  overlay: EditableGridOverlayDataFor<OverlayTargetType.Container>;
}

export const ContainerOverlayRenderer: React.FC<
  ContainerOverlayRendererProps
> = ({ overlay }) => {
  const Component = overlay.component;

  return (
    <div
      role="presentation"
      style={{
        gridRowStart: gridBoundingLines.row.start,
        gridRowEnd: gridBoundingLines.row.end,
        gridColumnStart: gridBoundingLines.col.start,
        gridColumnEnd: gridBoundingLines.col.end,
        zIndex: overlay.zIndex,
        pointerEvents: overlay.pointerEvents,
      }}
      className="relative"
    >
      {Component && <Component overlay={overlay} />}
    </div>
  );
};
