// src/lib/components/editable-grid/overlay-renderers/lines-overlay-renderer.component.tsx
import {
  type EditableGridOverlayDataFor,
  type OverlayTargetType,
} from "$/lib/components/editable-grid/editable-grid-overlay.model";
import {
  useGrid,
  useGridLines,
} from "$/lib/components/editable-grid/editable-grid.context";
import {
  GridLineAxis,
  gridEndLine,
  gridStartLine,
} from "$/lib/components/editable-grid/editable-grid.model";
import React, { useMemo } from "react";

export interface LinesOverlayRendererProps {
  overlay: EditableGridOverlayDataFor<OverlayTargetType.Lines>;
}

export const LinesOverlayRenderer: React.FC<LinesOverlayRendererProps> = ({
  overlay,
}) => {
  const grid = useGrid();
  const lines = useGridLines();

  const useLineBounds = overlay.options?.useLineBounds ?? true;
  const target = useMemo(
    () =>
      overlay.target ??
      [...lines.col, ...lines.row].filter(
        (line) => line.name !== gridStartLine && line.name !== gridEndLine,
      ),
    [overlay.target, lines],
  );

  return (
    <>
      {target.map((line) => {
        const axis = grid?.findLineAxis(line);
        const lineBounds = (useLineBounds && grid?.getLineBounds(line)) || null;
        const Component = overlay.component ?? React.Fragment;

        if (axis === GridLineAxis.Row) {
          return (
            <div
              key={axis + line.name}
              className="pointer-events-none relative"
              style={{
                gridRowStart: line.name,
                gridRowEnd: gridEndLine,
                gridColumnStart: lineBounds?.start.name ?? gridStartLine,
                gridColumnEnd: lineBounds?.end.name ?? gridEndLine,
                zIndex: overlay.zIndex,
              }}
            >
              <div
                className="relative h-0 w-full"
                style={{
                  pointerEvents: overlay.pointerEvents,
                }}
              >
                <Component
                  overlay={overlay}
                  line={line}
                  lineBounds={lineBounds}
                />
              </div>
            </div>
          );
        }

        return (
          <div
            key={axis + line.name}
            className="pointer-events-none relative"
            style={{
              gridRowStart: lineBounds?.start.name ?? gridStartLine,
              gridRowEnd: lineBounds?.end.name ?? gridEndLine,
              gridColumnStart: line.name,
              gridColumnEnd: gridEndLine,
              zIndex: overlay.zIndex,
            }}
          >
            <div
              className="relative h-full w-0"
              style={{
                pointerEvents: overlay.pointerEvents,
              }}
            >
              <Component
                overlay={overlay}
                line={line}
                lineBounds={lineBounds}
              />
            </div>
          </div>
        );
      })}
    </>
  );
};

// src/lib/components/editable-grid/overlay-renderers/lines-overlay-renderer.svelte
<script lang="ts">
	import { EditableGridController } from '$lib/components/editable-grid/editable-grid-controller';
	import type {
		EditableGridOverlayDataFor,
		OverlayTargetType,
	} from '$lib/components/editable-grid/editable-grid-overlay.model';
	import {
		GridLineAxis,
		gridContext,
		gridEndLine,
		gridStartLine,
	} from '$lib/components/editable-grid/editable-grid.model';
	import { getContext } from 'svelte';

	export let overlay: EditableGridOverlayDataFor<OverlayTargetType.Lines>;

	const grid = getContext<EditableGridController>(gridContext);
	let lines = grid.lines;

	$: useLineBounds = overlay.options?.useLineBounds ?? true;
	$: target =
		overlay.target ??
		[...$lines.col, ...$lines.row].filter(
			(line) => line.name !== gridStartLine && line.name !== gridEndLine,
		);
</script>

{#each target as line}
	{@const axis = grid.findLineAxis(line)}
	{@const lineBounds = useLineBounds ? grid.getLineBounds(line) : null}
	{#if axis === GridLineAxis.Row}
		<div
			style:grid-row-start={line.name}
			style:grid-row-end={gridEndLine}
			style:grid-column-start={lineBounds?.start.name ?? gridStartLine}
			style:grid-column-end={lineBounds?.end.name ?? gridEndLine}
			style:z-index={overlay.zIndex}
			class="pointer-events-none relative"
		>
			<div class="relative h-0 w-full" style:pointer-events={overlay.pointerEvents}>
				<svelte:component this={overlay.component} {overlay} {lineBounds} />
			</div>
		</div>
	{/if}
	{#if axis === GridLineAxis.Col}
		<div
			style:grid-column-start={line.name}
			style:grid-column-end={gridEndLine}
			style:grid-row-start={lineBounds?.start.name ?? gridStartLine}
			style:grid-row-end={lineBounds?.end.name ?? gridEndLine}
			style:z-index={overlay.zIndex}
			class="pointer-events-none relative"
		>
			<div class="relative h-full w-0" style:pointer-events={overlay.pointerEvents}>
				<svelte:component this={overlay.component} {overlay} {lineBounds} />
			</div>
		</div>
	{/if}
{/each}
